name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Setup Prism
        run: make prism-start
      - name: Restore Tests
        run: dotnet restore Test
      - name: Run Tests
        run: dotnet test Test/Test.csproj
        
